# Generated by Django 4.0.3 on 2022-03-02 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ads',
            new_name='Ad',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Image',
        ),
        migrations.RenameModel(
            old_name='Images',
            new_name='Service',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='path',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='path',
            new_name='name',
        ),
    ]
