# Generated by Django 4.0.3 on 2022-03-02 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_ads_ad_rename_services_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='creation_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='images',
            field=models.ManyToManyField(to='mainapp.image'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='services',
            field=models.ManyToManyField(to='mainapp.service'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mainapp.image'),
        ),
    ]
