# Generated by Django 4.0.3 on 2022-03-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_ad_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='path',
        ),
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.FileField(blank=True, upload_to='Images/', verbose_name='Files'),
        ),
    ]
