# Generated by Django 4.0.3 on 2022-03-16 13:32

from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_adimage_alter_user_image_delete_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='images',
        ),
        migrations.AddField(
            model_name='adimage',
            name='ad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.ad'),
            preserve_default=False,
        ),

    ]
