# Generated by Django 4.0.3 on 2022-03-16 13:57

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_ad_images_adimage_ad_alter_adimage_file'),
    ]

    operations = [

    ]
