# Generated by Django 4.0.3 on 2022-03-17 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_adimage_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdImage',
        ),
    ]
